### ISSUE TITLE
BG1 trap oddities

### ISSUE THREAD

**Issue by burner1024** [SpellholdStudios/BGT-WeiDU#13]
These relate to original BG1, and I'm not actually sure whether they should be considered bugs, but since BGT packs an internal fixpack, I guess that's the only place to post this:
1. Davaeorn's battle horror traps are detectable and disarmable (ar8603).
2. Several containers in Durlag's tower second level (ard011) have traps that are marked as detected from the beginning.

**Comment by skellytz** [comment]
1. I'm not sure about the battle horrors. Unlike the Temple of Bhaal traps, these have low skill requirements and are otherwise unavoidable. On the other hand, Trap 4 (Glyph of Warding) should be set to detectable (fixed in BGEE).

2. Yes, I agree they shouldn't have those flags (fixed in BGEE).

Thanks 😃

**Comment by burner1024** [comment]
Just for the record, it doesn't seem to me that they are supposed to be avoidable, lore- or metaknowledge-wise, but maybe that's just me.

(Still, they are detectable/disarmable _because_ of low skill requirements, so using them to justify it backwards isn't a very good argument).
