### ISSUE TITLE
64-bit cross-platform support

### ISSUE THREAD

**Issue by skellytz** [SpellholdStudios/BGT-WeiDU#4]
To do before release:
* Update TIS2BG2 to 64-bit versions
  * [x] Linux
  * [x] macOS
  * [ ] Windows
* Remove dependency on external binaries
  * [x] MOSunpack
  * [x] TISunpack

**Comment by Roberciiik** [comment]
In pull request #7 I've uploaded 64bit version of tis2bg2 for Linux and macOS. It should be tested with full installation before merging.

As I mentioned on SHS forum, for Windows x64 binary I would need to make some code changes. There is no official maintener of this tool so I suggest to create new repository for tis2bg2 here under SHS and take owenership of this. Then I could update code with history tracking instead of sending zip archive with code.

**Comment by skellytz** [comment]
Thank you 😃 I hope @GwendolyneFreddy will approve of creating the repo. I'd like to test both binaries myself, but I don't have a Mac on hand. I'll give the Linux version a shot and report back here.

**Comment by skellytz** [comment]
Tested on Ubuntu 19.10 (the same tis2bg2.log output).

**Comment by skellytz** [comment]
@Roberciiik, rather than starting a new repo, I've created a new branch: [tis2bg2](https://github.com/SpellholdStudios/BGT-WeiDU/tree/tis2bg2/bgt/install/src). This binary is an integral part of BGT and the updated source code could just as well be provided in the package. What do you think?

**Comment by Roberciiik** [comment]
Sure, as long as tis2bg2 is used in BGT installation process it can be a part of this repo. I will path code with my changes. Thanks.
