### ISSUE TITLE
Cursed scroll values inconsistent

### ISSUE THREAD

**Issue by HunterZ** [SpellholdStudios/BGT-WeiDU#58]
It seems that `SCRL17.ITM` and `SCRL18.ITM` have a value of zero, while all other cursed scrolls have a value of 300. This inconsistency prevents those two specific cursed scroll types from being sold.

**Comment by skellytz** [comment]
BG1: cursed scroll price is 0
BG2: cursed scroll price is 300 (except SCRL17 and SCRL18)

Cursed Scroll of Ailment (SCRL17) and Cursed Scroll of Stupidity (SCRL18) aren't available as in-game items in BG2; that's why their prices weren't changed from BG1 values.

BGT should use BG2 prices for all cursed scrolls by default.

Thanks!
